"""add enumeration

Revision ID: 943d1a990f25
Revises: 0002
Create Date: 2026-08-25 22:02:15.779535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '943d1a990f25'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussion_participant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('discussion_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussion.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('discussion', sa.Column('type_discussion', sa.Enum('DOSSIER', 'DIRECT', 'AGENCE', 'GLOBAL', name='typediscussionenum', native_enum=False, length=50), nullable=False))
    op.add_column('discussion', sa.Column('agence_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'discussion', 'agence', ['agence_id'], ['id'])
    op.add_column('notification', sa.Column('lien', sa.String(), nullable=True))
    op.alter_column('notification', 'dossier_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'dossier_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('notification', 'lien')
    op.drop_constraint(None, 'discussion', type_='foreignkey')
    op.drop_column('discussion', 'agence_id')
    op.drop_column('discussion', 'type_discussion')
    op.drop_table('discussion_participant')
    # ### end Alembic commands ###
